# Generated by Django 4.2.30 on 2026-05-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('audio_url', models.TextField(blank=True, null=True)),
                ('album_name', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
