# Generated by Django 4.2.30 on 2026-05-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial_song_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'liked_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('last_played', models.DateTimeField()),
            ],
            options={
                'db_table': 'play_history',
                'managed': False,
            },
        ),
    ]
