# Generated by Django 4.2.30 on 2026-05-15 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0002_likedsong_playhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('song', models.OneToOneField(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='music.song')),
                ('plain', models.TextField(blank=True, null=True)),
                ('synced', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'song_lyrics',
            },
        ),
        migrations.CreateModel(
            name='DownloadedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(db_column='song_id', on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'downloaded_songs',
                'unique_together': {('user', 'song')},
            },
        ),
    ]
