[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = tests.py
testpaths = accounts music playlists payments recommendations core
norecursedirs = .git venv __pycache__
markers =
  slow: slow tests (e.g., integration with external services)
  premium: tests requiring premium subscription
